# Docker compose file for local development mode
services:
 cloudinary-cli-dev:
    container_name: cloudinary-cli-dev
    image: weaponsforge/cloudinary-cli:dev
    env_file:
      - ./app/.env
    build:
      context: ./app
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./app:/opt/app
      - /opt/app/node_modules
    ports:
      - "9229:9229"     # VSCode debugger
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    restart: unless-stopped
